#! /bin/sh
# /etc/init.d/templog
# ### BEGIN INIT INFO
# Provides: templog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop templog
# Description: templog
### END INIT INFO


# . /etc/rc.d/init.d/functions  # uncomment/modify for your killproc

case "$1" in
    start)
    echo -n "Starting temperature logger: "
    echo -n "loading w1-gpio and w1-therm modules"
    /sbin/modprobe w1-gpio
    /sbin/modprobe w1-therm
    echo -n "setting gpio 1,2,3,15 to out"
    /usr/local/bin/gpio mode 1 out
    /usr/local/bin/gpio mode 2 out
    /usr/local/bin/gpio mode 4 out
    /usr/local/bin/gpio mode 15 out
    cd /root/raspberry.js.be/
    HOME=/root
    export DB_NAME=xxx
    export DB_HOST_NAME=xxx
    export DB_PORT=xxx
    export DB_USER_NAME=xxx
    export DB_PASSWORD=xxx
    /usr/local/bin/forever start run-cron.js   
    ;;

    stop)
    echo -n "Shutting down temperature logger:"
    HOME=/root
    /usr/local/bin/forever stop 0
    ;;


    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0

